version: "3.9"
services:
  # booking-backend:
  #   container_name: booking-backend
  #   image: booking-backend
  #   restart: always
  #   build:
  #     context: ./booking-backend
  #     dockerfile: Dockerfile
  #   env_file:
  #     - .env
  #   ports:
  #     - "${SERVER_PORT}:${SERVER_PORT}"
  #   networks:
  #     - booking
  #   depends_on:
  #     - booking-db

  bank-db:
    container_name: bank-db-container
    image: postgres
    restart: always
    hostname: ${POSTGRES_HOST}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
      # - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - bank_data:/var/lib/postgresql/data
    networks:
      - bank-network

networks:
  bank-network:
    name: bank-network

volumes:
  bank_data:
