version: "3.9"
services:
  bank-service:
    container_name: bank-service
    image: bank-service
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
      - bank-network
    depends_on:
      - bank-db
    entrypoint: ["/app/wait-for.sh", "bank-db:5432", "--", "/app/start.sh"]
    command: ["/app/main"]

  bank-db:
    container_name: bank-db
    image: postgres:12-alpine
    restart: always
    env_file: .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - bank_data:/var/lib/postgresql/data
    networks:
      - bank-network

networks:
  bank-network:
    name: bank-network

volumes:
  bank_data:
