name: build_test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
          POSTGRES_DB: bank_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Migration
        run: make migrateup

      - name: Test
        run: make test
